package pension_management_system.pension.member.mapper;

import org.mapstruct.*;
import pension_management_system.pension.member.dto.MemberRequest;
import pension_management_system.pension.member.dto.MemberResponse;
import pension_management_system.pension.member.entity.Member;

/**
 * MemberMapper - Converts between Entity and DTOs
 *
 * MapStruct automatically implements this interface at compile time
 * No need to write manual mapping code!
 *
 * @Mapper - Tells MapStruct to generate implementation
 * componentModel = "spring" - Makes it a Spring bean (can be injected)
 */

@Mapper(componentModel = "spring")
public interface MemberMapper {

    /**
     * Convert MemberRequest (DTO) to Member (Entity)
     * Used when creating new member
     */
    @Mapping(target = "id",  ignore = true)  // ID is auto-generated
    @Mapping(target = "memberId", ignore = true) // Autogenerated
//    @Mapping(target = "contributions", ignore = true) // Not set during creation
    @Mapping(target = "createdAt", ignore = true) // Auto-set by @CreationTimestamp
    @Mapping(target = "updatedAt", ignore = true) // Auto-set by @UpdateTimestamp
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    Member toEntity(MemberRequest request);

    /**
     * Convert Member (Entity) to MemberResponse (DTO)
     * Used when returning data to client
     */
    @Mapping(source = "employer.id", target = "employerId")
    @Mapping(source = "employer.companyName", target = "employerName")
    MemberResponse toResponse(Member member);

    /**
     * Update existing entity from request
     * Used when updating member
     */
    @Mapping(target = "id", ignore = true) // Don't update ID
    @Mapping(target = "memberId", ignore = true) // Don't update member ID
//    @Mapping(target = "contributions", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    void updateEntityFromRequest(MemberRequest request, @MappingTarget Member member);

}
