package pension_management_system.pension.benefit.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import pension_management_system.pension.benefit.entity.BenefitStatus;
import pension_management_system.pension.benefit.entity.BenefitType;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * BenefitResponse DTO - Data returned to client after creating/fetching benefits
 *
 * Purpose: Send benefit data to front-end without exposing internal database details
 *
 * Differences from BenefitRequest:
 * - Has ID (generated by database)
 * - Has status (PENDING, APPROVED, PAID, etc.)
 * - Has approval/payment dates
 * - Has audit fields (createdAt, updatedAt)
 * - Has member details (instead of just memberId)
 *
 * Example JSON Response:
 * {
 *   "id": 1,
 *   "memberFirstName": "John",
 *   "memberLastName": "Doe",
 *   "memberId": 123,
 *   "benefitType": "RETIREMENT",
 *   "status": "APPROVED",
 *   "requestedAmount": 50000.00,
 *   "approvedAmount": 48000.00,
 *   "applicationDate": "2025-01-15",
 *   "approvalDate": "2025-01-20",
 *   "approvedBy": "admin@pension.com",
 *   "notes": "Approved for retirement benefit",
 *   "createdAt": "2025-01-15T10:30:00",
 *   "updatedAt": "2025-01-20T14:45:00"
 * }
 *
 * @Builder - Lombok generates builder pattern for creating objects
 * Example: BenefitResponse.builder().id(1).status("PAID").build()
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BenefitResponse {

    /**
     * DATABASE ID
     * Auto-generated by database
     * Used for updates and deletes
     */
    private Long id;

    /**
     * MEMBER DETAILS
     * Instead of returning full Member object, we return key fields
     * This prevents circular references and reduces response size
     */
    private Long memberId;  // Member's database ID
    private String memberFirstName;
    private String memberLastName;
    private String memberEmail;

    /**
     * BENEFIT DETAILS
     */
    private BenefitType benefitType;
    private BenefitStatus status;

    /**
     * AMOUNTS
     * requestedAmount - What member asked for
     * approvedAmount - What was actually approved (may be different)
     */
    private BigDecimal requestedAmount;
    private BigDecimal approvedAmount;

    /**
     * DATES
     * applicationDate - When member applied
     * approvalDate - When claim was approved (null if not approved yet)
     * paymentDate - When money was paid (null if not paid yet)
     */
    private LocalDate applicationDate;
    private LocalDate approvalDate;
    private LocalDate paymentDate;

    /**
     * APPROVAL DETAILS
     * approvedBy - Who approved/rejected the claim
     * rejectionReason - Why it was rejected (if status = REJECTED)
     */
    private String approvedBy;
    private String rejectionReason;

    /**
     * NOTES
     * Additional comments about the claim
     */
    private String notes;

    /**
     * AUDIT FIELDS
     * When record was created and last updated
     * Useful for tracking changes
     */
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
