package pension_management_system.pension.report.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Report Entity - Represents a generated report in the system
 *
 * Purpose: Track all reports generated by the pension management system
 * Stores metadata about reports including who requested them, when they were generated,
 * type, format, parameters, and where the file is stored.
 *
 * Why track reports?
 * - Audit trail: Know who generated what and when
 * - Re-download: Users can download previously generated reports
 * - Performance: Avoid regenerating same report multiple times
 * - Analytics: Track which reports are most used
 * - Compliance: Regulatory requirements to track report access
 *
 * Database Table: reports
 *
 * Annotations Explained:
 * @Entity - Marks this as a JPA entity (maps to database table)
 * @Table - Specifies table name in database
 * @Data - Lombok generates getters, setters, toString, equals, hashCode
 * @Builder - Lombok enables builder pattern: Report.builder().title("...").build()
 * @NoArgsConstructor - Generates no-argument constructor (required by JPA)
 * @AllArgsConstructor - Generates constructor with all fields (used by @Builder)
 */
@Entity
@Table(name = "reports")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Report {

    /**
     * UNIQUE IDENTIFIER
     *
     * Primary key for the report record
     * Auto-generated by database (auto-increment)
     *
     * Example: 1, 2, 3, ...
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * REPORT TITLE
     *
     * Human-readable title for the report
     * Displayed in report list and download history
     *
     * Examples:
     * - "Member Statement - John Doe (Jan 2025)"
     * - "Monthly Contribution Summary - January 2025"
     * - "Employer Report - Tech Corp Ltd"
     *
     * Validation: Cannot be null, max 255 characters
     */
    @Column(nullable = false, length = 255)
    private String title;

    /**
     * REPORT TYPE
     *
     * Category of report being generated
     * Determines what data is included and how it's formatted
     *
     * Possible values (from ReportType enum):
     * - MEMBER_STATEMENT: Individual member contribution history
     * - EMPLOYER_REPORT: Employer's member and contribution summary
     * - CONTRIBUTION_SUMMARY: Contribution totals by period
     * - BENEFIT_CLAIMS: Benefit claims summary
     * - ANALYTICS_DASHBOARD: System-wide analytics export
     * - AUDIT_TRAIL: System activity logs
     *
     * @Enumerated(EnumType.STRING) - Store enum as text in database
     * (Stores "MEMBER_STATEMENT" instead of 0, 1, 2... for readability)
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 50)
    private ReportType reportType;

    /**
     * OUTPUT FORMAT
     *
     * File format of the generated report
     *
     * Possible values (from ReportFormat enum):
     * - PDF: Portable Document Format (best for printing and official documents)
     * - EXCEL: Microsoft Excel spreadsheet (best for data analysis)
     * - CSV: Comma-Separated Values (best for importing to other systems)
     *
     * Different formats serve different purposes:
     * - PDF: Official statements, archival
     * - EXCEL: Financial analysis, pivot tables
     * - CSV: Data transfer, bulk processing
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private ReportFormat format;

    /**
     * GENERATION TIMESTAMP
     *
     * When the report was generated
     * Automatically set when report is created
     *
     * Example: 2025-01-15 10:30:45
     *
     * Used for:
     * - Sorting reports by date (newest first)
     * - Displaying "Generated on: ..." in UI
     * - Audit trail
     * - Auto-cleanup of old reports
     */
    @Column(nullable = false)
    private LocalDateTime generatedAt;

    /**
     * REQUESTED BY (USER)
     *
     * Username or email of person who requested the report
     * For audit trail and security
     *
     * Examples:
     * - "admin@pensionsystem.com"
     * - "john.doe@company.com"
     * - "system" (for automated reports)
     *
     * Why track this?
     * - Security: Know who accessed what data
     * - Compliance: Regulatory requirements
     * - Support: Help users find their reports
     * - Analytics: Track which users generate most reports
     */
    @Column(nullable = false, length = 255)
    private String requestedBy;

    /**
     * ENTITY ID (OPTIONAL)
     *
     * ID of the specific entity this report is about
     * Depends on report type:
     *
     * - MEMBER_STATEMENT → Member ID
     * - EMPLOYER_REPORT → Employer ID
     * - CONTRIBUTION_SUMMARY → null (system-wide)
     * - BENEFIT_CLAIMS → Member ID or null (all claims)
     *
     * Example use case:
     * - If reportType = MEMBER_STATEMENT and entityId = 123
     *   Then this is a statement for member #123
     *
     * nullable = true because some reports are system-wide (no specific entity)
     */
    @Column(nullable = true)
    private Long entityId;

    /**
     * DATE RANGE START (OPTIONAL)
     *
     * Start date for report data filtering
     * Used for period-based reports
     *
     * Examples:
     * - Monthly report: 2025-01-01
     * - Quarterly report: 2025-01-01
     * - Custom range: 2024-06-15
     *
     * If null: Report includes all data up to endDate or all time
     *
     * Use case:
     * "Generate contribution summary from Jan 1, 2025 to Jan 31, 2025"
     * startDate = 2025-01-01
     * endDate = 2025-01-31
     */
    @Column(nullable = true)
    private LocalDateTime startDate;

    /**
     * DATE RANGE END (OPTIONAL)
     *
     * End date for report data filtering
     * Used for period-based reports
     *
     * If null: Report includes data up to current date
     */
    @Column(nullable = true)
    private LocalDateTime endDate;

    /**
     * REPORT PARAMETERS (OPTIONAL)
     *
     * Additional filter criteria or settings used to generate report
     * Stored as JSON string for flexibility
     *
     * Examples:
     * - {"status": "APPROVED", "minAmount": 5000}
     * - {"employerId": 123, "contributionType": "MONTHLY"}
     * - {"includeGraphs": true, "currency": "NGN"}
     *
     * Why JSON?
     * - Different reports need different parameters
     * - Flexible schema (can add new parameters without changing database)
     * - Can reconstruct exact report settings for re-generation
     *
     * @Column(columnDefinition = "TEXT") - Allows storing large JSON strings
     */
    @Column(columnDefinition = "TEXT", nullable = true)
    private String parameters;

    /**
     * FILE PATH
     *
     * Location where the generated report file is stored
     * Relative or absolute path on server
     *
     * Examples:
     * - "reports/2025/01/member_statement_123_20250115_103045.pdf"
     * - "/var/pension/reports/employer_report_456.xlsx"
     * - "s3://pension-reports/contribution_summary.csv"
     *
     * Used for:
     * - Downloading previously generated reports
     * - Cleanup old report files
     * - Backup and archival
     *
     * Best practices:
     * - Include timestamp to avoid collisions
     * - Organize by date/type for easy management
     * - Use secure storage with access controls
     */
    @Column(nullable = false, length = 500)
    private String filePath;

    /**
     * FILE SIZE (BYTES)
     *
     * Size of the generated report file in bytes
     * Helps with storage management and user experience
     *
     * Examples:
     * - 15360 bytes = 15 KB (small PDF)
     * - 524288 bytes = 512 KB (medium Excel)
     * - 5242880 bytes = 5 MB (large report with images)
     *
     * Used for:
     * - Displaying file size to user: "2.5 MB"
     * - Storage quota management
     * - Monitoring system storage usage
     * - Warning users about large downloads
     *
     * How to display:
     * - < 1024 bytes: Show as bytes (512 B)
     * - < 1048576 bytes: Show as KB (256 KB)
     * - >= 1048576 bytes: Show as MB (2.5 MB)
     */
    @Column(nullable = false)
    private Long fileSize;

    /**
     * GENERATION STATUS
     *
     * Current status of report generation
     * Important for async/background report generation
     *
     * Possible values (as String enum):
     * - "PENDING": Report queued for generation
     * - "PROCESSING": Currently being generated
     * - "COMPLETED": Successfully generated and ready for download
     * - "FAILED": Generation failed (check error message)
     *
     * Workflow:
     * 1. User requests report → Status = PENDING
     * 2. Background job picks it up → Status = PROCESSING
     * 3. Generation succeeds → Status = COMPLETED
     *    OR Generation fails → Status = FAILED
     *
     * Why async?
     * - Large reports can take minutes to generate
     * - Don't block user's browser
     * - Better server resource management
     */
    @Column(nullable = false, length = 20)
    @Builder.Default
    private String status = "COMPLETED";

    /**
     * ERROR MESSAGE (OPTIONAL)
     *
     * Details of error if report generation failed
     * Helps with debugging and user support
     *
     * Examples:
     * - "Database connection timeout"
     * - "Invalid date range: start date after end date"
     * - "Member ID 999 not found"
     * - "Insufficient permissions to view employer data"
     *
     * Only populated when status = "FAILED"
     * Null when status = "COMPLETED"
     *
     * Best practices:
     * - Log detailed technical error in server logs
     * - Store user-friendly message here
     * - Don't expose sensitive system information
     */
    @Column(columnDefinition = "TEXT", nullable = true)
    private String errorMessage;

    /**
     * HELPER METHOD: Check if report generation is complete
     *
     * Useful for conditional logic in UI
     *
     * Example usage:
     * if (report.isCompleted()) {
     *     showDownloadButton();
     * } else {
     *     showProcessingSpinner();
     * }
     */
    public boolean isCompleted() {
        return "COMPLETED".equals(this.status);
    }

    /**
     * HELPER METHOD: Check if report generation failed
     *
     * Example usage:
     * if (report.isFailed()) {
     *     displayErrorMessage(report.getErrorMessage());
     * }
     */
    public boolean isFailed() {
        return "FAILED".equals(this.status);
    }

    /**
     * HELPER METHOD: Mark report as completed
     *
     * Called when report generation finishes successfully
     *
     * @param filePath Where the report file is saved
     * @param fileSize Size of generated file in bytes
     */
    public void markAsCompleted(String filePath, Long fileSize) {
        this.status = "COMPLETED";
        this.filePath = filePath;
        this.fileSize = fileSize;
        this.errorMessage = null; // Clear any previous error
    }

    /**
     * HELPER METHOD: Mark report as failed
     *
     * Called when report generation encounters an error
     *
     * @param errorMessage Description of what went wrong
     */
    public void markAsFailed(String errorMessage) {
        this.status = "FAILED";
        this.errorMessage = errorMessage;
    }

    /**
     * HELPER METHOD: Get human-readable file size
     *
     * Converts bytes to KB/MB for display
     *
     * Examples:
     * - 512 bytes → "512 B"
     * - 15360 bytes → "15 KB"
     * - 5242880 bytes → "5.0 MB"
     *
     * @return Formatted file size string
     */
    public String getFormattedFileSize() {
        if (fileSize == null) return "Unknown";

        if (fileSize < 1024) {
            return fileSize + " B";
        } else if (fileSize < 1048576) {
            return String.format("%.1f KB", fileSize / 1024.0);
        } else {
            return String.format("%.1f MB", fileSize / 1048576.0);
        }
    }
}
